[build]
  base = "docs"
  command = "npm run build"
  publish = "docs/.vuepress/dist"

[[redirects]]
  from = "https://nuxtstack.netlify.com/*"
  to = "https://nuxtstack.org/:splat"
  force = true

# EXAMPLE: BENCHMARK

[context.benchmark-example]
  base = "examples/benchmark"
  command = "nuxt init -p basic && npm run generate"
  publish = "examples/benchmark/dist"

[context.benchmark-stats]
  base = "examples/bench"
  command = "nuxt init -p basic && npm run stats"
  publish = "examples/benchmark/.nuxt/stats"

# EXAMPLE: BASIC

[context.basic-example]
  base = "examples/basic"
  command = "nuxt init -p basic && npm run generate"
  publish = "examples/basic/dist"

[context.basic-stats]
  base = "examples/bench"
  command = "nuxt init -p basic && npm run stats"
  publish = "examples/basic/.nuxt/stats"

# EXAMPLE: FANCY

[context.fancy-example]
  base = "examples/fancy"
  command = "nuxt init -p fancy && npm run generate"
  publish = "examples/fancy/dist"

[context.fancy-stats]
  base = "examples/bench"
  command = "nuxt init -p fancy && npm run stats"
  publish = "examples/fancy/.nuxt/stats"
